language: node_js
node_js:
  - "6"
  - "5"

env:
  - CXX=clang
  - PATH=$PATH:.

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6

compiler: clang

sudo: false

os:
  - linux
  - osx

osx_image: xcode7.2

before_install:
  - node --version
  - npm --version
  - gcc --version
  - chmod +x install-modules.sh
  - npm run initialize

script:
  - chmod +x test.sh
  - export PATH=$PATH:.
  - npm run test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules